Cryptic Cabinet: CrypticCabinet.GameManagement.GameManager Class Reference
CrypticCabinet.GameManagement.GameManager Class Reference
This class manages the game phases dynamically. This is a singleton for convenience, so that from any part of the game anything can request to proceed to the next phase of the gameplay if desired.
Public Member Functions
void StartGameplay ()
Starts the gameplay by initializing the current game phase and running it.
void RestartGameplay ()
Restart the flow for the entire gameplay. Call this function if you need to re-initialize the game management to the initial state.
void NextGameplayPhase ()
Jumps to the next gameplay phase. If no more phases are available, the end of gameplay is reached and nothing happens.
GamePhase GetCurrentGamePhase ()
Returns the current game phase of the gameplay.
Public Attributes
bool GameWasRestarted
Action OnGamePhaseChanged
Protected Member Functions
override void InternalAwake ()
Performed on Awake to ensure that the initial configuration is valid.
Detailed Description
This class manages the game phases dynamically. This is a singleton for convenience, so that from any part of the game anything can request to proceed to the next phase of the gameplay if desired.
Member Function Documentation
GetCurrentGamePhase()
GamePhase CrypticCabinet.GameManagement.GameManager.GetCurrentGamePhase ()
Returns the current game phase of the gameplay.
Returns
The current game phase, or null if the gameplay was not started yet.
Referenced by CrypticCabinet.UI.UISystem.ShowMainMenu(), and CrypticCabinet.UI.Modal.InGameMenu.ToggleInGameMenu().
InternalAwake()
override void CrypticCabinet.GameManagement.GameManager.InternalAwake () protected
Performed on Awake to ensure that the initial configuration is valid.
NextGameplayPhase()
void CrypticCabinet.GameManagement.GameManager.NextGameplayPhase ()
Jumps to the next gameplay phase. If no more phases are available, the end of gameplay is reached and nothing happens.
Referenced by CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase.InitializeInternal(), CrypticCabinet.GameManagement.Timeline.TimelineGamePhase.InitializeInternal(), CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.InitializeInternal(), and CrypticCabinet.GameManagement.SkipGamePhase.Update().
RestartGameplay()
void CrypticCabinet.GameManagement.GameManager.RestartGameplay ()
Restart the flow for the entire gameplay. Call this function if you need to re-initialize the game management to the initial state.
Referenced by CrypticCabinet.UI.Modal.Credits.OnBackClicked(), and CrypticCabinet.Colocation.ColocationDriverNetObj.RetryColocation().
StartGameplay()
void CrypticCabinet.GameManagement.GameManager.StartGameplay ()
Starts the gameplay by initializing the current game phase and running it.
References CrypticCabinet.Photon.PhotonConnector.Runner, and CrypticCabinet.UI.UISystem.ShowMessage().
Member Data Documentation
GameWasRestarted
bool CrypticCabinet.GameManagement.GameManager.GameWasRestarted
OnGamePhaseChanged
Action CrypticCabinet.GameManagement.GameManager.OnGamePhaseChanged
The documentation for this class was generated from the following file:
GameManager.cs