Cryptic Cabinet: CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase Class Reference
CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase Class Reference
Simple game phase where a message is shown to the Host asking for pressing a "start game" button that will force all new future guests to be forbidden from joining the game. When the "start game" button is pressed, the game officially starts for all joined players.
Protected Member Functions
override void InitializeInternal ()
override void DeinitializeInternal ()
Additional Inherited Members
Public Member Functions inherited from CrypticCabinet.GameManagement.GamePhase
void Initialize ()
void Deinitialize ()
Detailed Description
Simple game phase where a message is shown to the Host asking for pressing a "start game" button that will force all new future guests to be forbidden from joining the game. When the "start game" button is pressed, the game officially starts for all joined players.
Member Function Documentation
DeinitializeInternal()
override void CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.DeinitializeInternal () protected virtual
Reimplemented from CrypticCabinet.GameManagement.GamePhase.
InitializeInternal()
override void CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.InitializeInternal () protected virtual
Reimplemented from CrypticCabinet.GameManagement.GamePhase.
References CrypticCabinet.UI.UISystem.HideAll(), CrypticCabinet.Photon.PhotonConnector.HostAllowGuests(), CrypticCabinet.Photon.PhotonConnector.IsMasterClient(), CrypticCabinet.Photon.PhotonConnector.IsMultiplayerSession, CrypticCabinet.GameManagement.GameManager.NextGameplayPhase(), and CrypticCabinet.Photon.PhotonConnector.Runner.
The documentation for this class was generated from the following file:
WaitForGuestsPhase.cs