Cryptic Cabinet: CrypticCabinet.Utils.PendingTasksHandler Class Reference
CrypticCabinet.Utils.PendingTasksHandler Class Reference
An utility class that can execute a sequence of pending actions at a later time. It offers a mechanism to perform an action immediately if it can be executed, or to delay its execution to a future time once it can be executed.
Public Member Functions
delegate void PendingAction ()
Defines a void pending action that can be executed immediately or as a pending action in the future.
void TryExecuteAction (PendingAction action, bool canExecuteNow)
Try to execute the function if canExecuteNow is true, otherwise add it to the queue of pending actions that can then be sequentially executed when ExecutePendingActions() is called.
void ExecuteAllOrClear (bool canExecuteAll)
If canExecuteAll is true, executes all pending actions sequentially. If canExecuteAll is false, remove all existing pending actions from the list.
void ClearActions ()
Clears all pending actions, if they are not running at the moment.
void ExecutePendingActions ()
Sequentially executes all the pending actions.
Detailed Description
An utility class that can execute a sequence of pending actions at a later time. It offers a mechanism to perform an action immediately if it can be executed, or to delay its execution to a future time once it can be executed.
Member Function Documentation
ClearActions()
void CrypticCabinet.Utils.PendingTasksHandler.ClearActions ()
Clears all pending actions, if they are not running at the moment.
Referenced by CrypticCabinet.Utils.PendingTasksHandler.ExecuteAllOrClear(), and CrypticCabinet.Utils.PendingTasksHandler.ExecutePendingActions().
ExecuteAllOrClear()
void CrypticCabinet.Utils.PendingTasksHandler.ExecuteAllOrClear (bool canExecuteAll)
If canExecuteAll is true, executes all pending actions sequentially. If canExecuteAll is false, remove all existing pending actions from the list.
Parameters
canExecuteAll True to execute all, false to clear all.
References CrypticCabinet.Utils.PendingTasksHandler.ClearActions(), and CrypticCabinet.Utils.PendingTasksHandler.ExecutePendingActions().
ExecutePendingActions()
void CrypticCabinet.Utils.PendingTasksHandler.ExecutePendingActions ()
Sequentially executes all the pending actions.
References CrypticCabinet.Utils.PendingTasksHandler.ClearActions().
Referenced by CrypticCabinet.Utils.PendingTasksHandler.ExecuteAllOrClear().
PendingAction()
delegate void CrypticCabinet.Utils.PendingTasksHandler.PendingAction ()
Defines a void pending action that can be executed immediately or as a pending action in the future.
TryExecuteAction()
void CrypticCabinet.Utils.PendingTasksHandler.TryExecuteAction (PendingAction action, bool canExecuteNow)
Try to execute the function if canExecuteNow is true, otherwise add it to the queue of pending actions that can then be sequentially executed when ExecutePendingActions() is called.
Parameters
action The action to perform.
canExecuteNow True if we can execute the action now, false otherwise.
The documentation for this class was generated from the following file:
PendingTasksHandler.cs