Cryptic Cabinet: CrypticCabinet.Utils.ObjectPlacementManager Class Reference
CrypticCabinet.Utils.ObjectPlacementManager Class Reference
The manager responsible for the object placements in the room during scene setup.
Classes
struct SceneObject
Public Types
enum LoadableSceneObjects {
ORRERY , CABINET , SAND_SHOOT , WINDOW_PULLY ,
LIGHT_PLATE , BUCKET , MINI_GENERATOR_SMALL , MAIN_GENERATOR ,
MAIN_GENERATOR_COIL , GENERATOR_SCHEMATIC1 , DIRECTIONAL_APPARATUS , MINI_GENERATOR_MEDIUM ,
MINI_GENERATOR_LARGE , ATLAS_STATUE , LIGHT_BULB_UV_MACHINE , UV_SIGN_CLUE ,
UV_SIGN_TEXT1 , UV_SIGN_TEXT2 , UV_SIGN_TEXT3 , SAFE_PUZZLE ,
GENERATOR_SCHEMATIC2
}
Public Member Functions
ObjectPlacementManager (SceneObject o)
void ConfirmObjectPlacements ()
void CleanUp ()
async void ShufflePlacements ()
List< SceneObject > RequestObjects (LoadableSceneObjects objectType)
void UpdatePlacedObject (LoadableSceneObjects objectType, Vector3 mainPosition, Vector3 wallPosition, Quaternion mainRotation, Quaternion wallRotation)
Public Attributes
Action ConfirmObjectPlacementsCallback
Protected Member Functions
override void InternalAwake ()
Detailed Description
The manager responsible for the object placements in the room during scene setup.
Member Enumeration Documentation
LoadableSceneObjects
enum CrypticCabinet.Utils.ObjectPlacementManager.LoadableSceneObjects
Enumerator
ORRERY
CABINET
SAND_SHOOT
WINDOW_PULLY
LIGHT_PLATE
BUCKET
MINI_GENERATOR_SMALL
MAIN_GENERATOR
MAIN_GENERATOR_COIL
GENERATOR_SCHEMATIC1
DIRECTIONAL_APPARATUS
MINI_GENERATOR_MEDIUM
MINI_GENERATOR_LARGE
ATLAS_STATUE
LIGHT_BULB_UV_MACHINE
UV_SIGN_CLUE
UV_SIGN_TEXT1
UV_SIGN_TEXT2
UV_SIGN_TEXT3
SAFE_PUZZLE
GENERATOR_SCHEMATIC2
Constructor & Destructor Documentation
ObjectPlacementManager()
CrypticCabinet.Utils.ObjectPlacementManager.ObjectPlacementManager (SceneObject o)
Member Function Documentation
CleanUp()
void CrypticCabinet.Utils.ObjectPlacementManager.CleanUp ()
Referenced by CrypticCabinet.Utils.ObjectPlacementManager.ConfirmObjectPlacements(), and CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase.DeinitializeInternal().
ConfirmObjectPlacements()
void CrypticCabinet.Utils.ObjectPlacementManager.ConfirmObjectPlacements ()
References CrypticCabinet.Utils.ObjectPlacementManager.CleanUp(), and CrypticCabinet.Utils.ObjectPlacementManager.ConfirmObjectPlacementsCallback.
InternalAwake()
override void CrypticCabinet.Utils.ObjectPlacementManager.InternalAwake () protected
RequestObjects()
List< SceneObject > CrypticCabinet.Utils.ObjectPlacementManager.RequestObjects (LoadableSceneObjects objectType)
Referenced by CrypticCabinet.Utils.SimpleSceneObjectPlacer.PlaceUsingSpawner().
ShufflePlacements()
async void CrypticCabinet.Utils.ObjectPlacementManager.ShufflePlacements ()
UpdatePlacedObject()
void CrypticCabinet.Utils.ObjectPlacementManager.UpdatePlacedObject (LoadableSceneObjects objectType, Vector3 mainPosition, Vector3 wallPosition, Quaternion mainRotation, Quaternion wallRotation)
Referenced by CrypticCabinet.Utils.ObjectPlacementVisualiser.UpdateLocation().
Member Data Documentation
ConfirmObjectPlacementsCallback
Action CrypticCabinet.Utils.ObjectPlacementManager.ConfirmObjectPlacementsCallback
Referenced by CrypticCabinet.Utils.ObjectPlacementManager.ConfirmObjectPlacements().
The documentation for this class was generated from the following file:
ObjectPlacementManager.cs