Cryptic Cabinet: CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator Class Reference
CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator Class Reference
Represents an object that can emit electricity arcs from a start to an end position. The end position is based on other electric generators nearby, which are distant not less than the m_electricMaxRadius. When the generator's electricity is disabled, no electricity arc will be shown.
Public Member Functions
void InjectElectricGeneratorManager (ElectricGeneratorsManager manager)
Injects the electric generator manager that handles the tesla puzzle pieces.
void SwitchOn ()
Switch the electric generator on, for all users in game session via RPC.
void SwitchOff ()
Switch the electric generator off, for all users in game session via RPC.
bool IsSwitchedOn ()
Return true if the electric generator is switched on, false otherwise.
void TogglePowerSwitch ()
Toggle the power switch for this electric generator. If switched on it is switched off, and viceversa.
Static Public Member Functions
static void UpdatePowerStatus (Changed< ElectricGenerator > changed)
Updates the power status UI for the electric generator.
Properties
ElectricGeneratorID GeneratorID [get]
int Voltage [get]
bool IsInPlace [get, set]
True if the generator is snapped to the expected position.
Detailed Description
Represents an object that can emit electricity arcs from a start to an end position. The end position is based on other electric generators nearby, which are distant not less than the m_electricMaxRadius. When the generator's electricity is disabled, no electricity arc will be shown.
Member Function Documentation
InjectElectricGeneratorManager()
void CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.InjectElectricGeneratorManager (ElectricGeneratorsManager manager)
Injects the electric generator manager that handles the tesla puzzle pieces.
Parameters
manager
IsSwitchedOn()
bool CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.IsSwitchedOn ()
Return true if the electric generator is switched on, false otherwise.
Returns
True if the electric generator is switched on, false otherwise.
SwitchOff()
void CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.SwitchOff ()
Switch the electric generator off, for all users in game session via RPC.
Referenced by CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.TogglePowerSwitch().
SwitchOn()
void CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.SwitchOn ()
Switch the electric generator on, for all users in game session via RPC.
Referenced by CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.TogglePowerSwitch().
TogglePowerSwitch()
void CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.TogglePowerSwitch ()
Toggle the power switch for this electric generator. If switched on it is switched off, and viceversa.
References CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.SwitchOff(), and CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.SwitchOn().
UpdatePowerStatus()
static void CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.UpdatePowerStatus (Changed< ElectricGenerator > changed) static
Updates the power status UI for the electric generator.
Parameters
changed The electric generator that changed its status.
Property Documentation
GeneratorID
ElectricGeneratorID CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.GeneratorID get
IsInPlace
bool CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.IsInPlace get set
True if the generator is snapped to the expected position.
Voltage
int CrypticCabinet.Puzzles.TeslaPuzzle.ElectricGenerator.Voltage get
The documentation for this class was generated from the following file:
ElectricGenerator.cs