Cryptic Cabinet: CrypticCabinet.SceneManagement.WallSpaceFinder Class Reference
CrypticCabinet.SceneManagement.WallSpaceFinder Class Reference
Used to detect empty spaces on a wall for the object placement queries.
Public Member Functions
WallSpaceFinder (Material debugMaterial=null)
Passing the material allows the use of the debug view of the cells.
void CleanUp ()
Cleans up the generated cells, call this when the space finder is no longer needed.
void ToggleCellVisibility ()
Toggles the debug cells if the debug material was provided.
void SetDebugVisible (bool visible)
Sets the debug cell visibility if the debug material was provided.
void AddWall (Transform wallTransform, Vector2 bounds)
Uses the position matrix and the bounds of a wall to generate the cells used to find safe locations on wall surfaces. This assumes the location provided is in the middle of the wall. Note: All walls should be added before trying to add any other scene objects or request a wall location.
void AddPlaneObject (Matrix4x4 objectLocationMatrix, Vector2 objectDimensions)
Calculates what cells a 2D object blocks and flags affected cells.
void AddVolumeObject (Matrix4x4 objectLocationMatrix, Vector3 objectDimensions)
Searches the cell representation of the room for the given object and flags the blocked cells.
bool QueryForSafeWallLocation (float heightOffFloor, float objectHeight, float objectWidth, Vector2 edgeDistance, out Vector3 position, out Quaternion rotation, bool ignoreSceneBlocked, bool markAsBlocked=true)
Finds a random cell roughly at the requested height. Returned cell is likely not actually at the height request.
bool RequestRandomLocationCustomWithFloor (float halfDepth, float width, float height, Vector2 edgeDistance, out Vector3 position, out Quaternion rotation, Func< Collider[], int, bool > checkPhysicsResultIsClear, Action< Collider[], int > blockPhysicsResult, bool markAsBlocked)
void PickRandomWallCell (float minHeight, out Vector3 position, out Quaternion rotation)
void SetWallCollidersEnabled (bool wallsEnabled)
Sets the active state of the colliders used for finding safe wall locations.
void ResetWallPlacements ()
Public Attributes
float TargetCellSize = 0.5f
The target size of the cells. This adjusted to ensure the cells fit the wall perfectly.
Detailed Description
Used to detect empty spaces on a wall for the object placement queries.
Constructor & Destructor Documentation
WallSpaceFinder()
CrypticCabinet.SceneManagement.WallSpaceFinder.WallSpaceFinder (Material debugMaterial = null)
Passing the material allows the use of the debug view of the cells.
Parameters
debugMaterial Material used for debug cell view, passing null disables the debug view.
Member Function Documentation
AddPlaneObject()
void CrypticCabinet.SceneManagement.WallSpaceFinder.AddPlaneObject (Matrix4x4 objectLocationMatrix, Vector2 objectDimensions)
Calculates what cells a 2D object blocks and flags affected cells.
Parameters
objectLocationMatrix The matrix describing the position and rotation of the object being added.
objectDimensions The size of the object.
References CrypticCabinet.SceneManagement.WallSpaceFinder.AddVolumeObject().
AddVolumeObject()
void CrypticCabinet.SceneManagement.WallSpaceFinder.AddVolumeObject (Matrix4x4 objectLocationMatrix, Vector3 objectDimensions)
Searches the cell representation of the room for the given object and flags the blocked cells.
Parameters
objectLocationMatrix The matrix describing the position and rotation of the object being added.
objectDimensions The size of the object.
Referenced by CrypticCabinet.SceneManagement.WallSpaceFinder.AddPlaneObject().
AddWall()
void CrypticCabinet.SceneManagement.WallSpaceFinder.AddWall (Transform wallTransform, Vector2 bounds)
Uses the position matrix and the bounds of a wall to generate the cells used to find safe locations on wall surfaces. This assumes the location provided is in the middle of the wall. Note: All walls should be added before trying to add any other scene objects or request a wall location.
Parameters
wallTransform The wall transform for position and rotation.
bounds The size of the wall.
References CrypticCabinet.Utils.StringConstants.SCENE_UNDERSTANDING_LAYER, and CrypticCabinet.SceneManagement.WallSpaceFinder.TargetCellSize.
CleanUp()
void CrypticCabinet.SceneManagement.WallSpaceFinder.CleanUp ()
Cleans up the generated cells, call this when the space finder is no longer needed.
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.CleanUp().
PickRandomWallCell()
void CrypticCabinet.SceneManagement.WallSpaceFinder.PickRandomWallCell (float minHeight, out Vector3 position, out Quaternion rotation)
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestTotallyRandomWallLocation().
QueryForSafeWallLocation()
bool CrypticCabinet.SceneManagement.WallSpaceFinder.QueryForSafeWallLocation (float heightOffFloor, float objectHeight, float objectWidth, Vector2 edgeDistance, out Vector3 position, out Quaternion rotation, bool ignoreSceneBlocked, bool markAsBlocked = true)
Finds a random cell roughly at the requested height. Returned cell is likely not actually at the height request.
Parameters
heightOffFloor The height to search for.
objectHeight The height of the object for the requested cell.
objectWidth The width of the object for the requested cell.
edgeDistance The minimum distance from the wall edge, x: left y: right
position The position of the resulting cell.
rotation The rotation of the resulting cell.
ignoreSceneBlocked Flag to indicate if this should allow being placed over scene blocked cells.
markAsBlocked When true, the returned cell is marked as blocked, otherwise it is unchanged.
Returns
Transform of the found cell.
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestRandomWallLocation().
RequestRandomLocationCustomWithFloor()
bool CrypticCabinet.SceneManagement.WallSpaceFinder.RequestRandomLocationCustomWithFloor (float halfDepth, float width, float height, Vector2 edgeDistance, out Vector3 position, out Quaternion rotation, Func< Collider[], int, bool > checkPhysicsResultIsClear, Action< Collider[], int > blockPhysicsResult, bool markAsBlocked)
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestRandomFloorWallLocation().
ResetWallPlacements()
void CrypticCabinet.SceneManagement.WallSpaceFinder.ResetWallPlacements ()
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.ResetSceneUnderstanding().
SetDebugVisible()
void CrypticCabinet.SceneManagement.WallSpaceFinder.SetDebugVisible (bool visible)
Sets the debug cell visibility if the debug material was provided.
Parameters
visible True to enable the cells.
SetWallCollidersEnabled()
void CrypticCabinet.SceneManagement.WallSpaceFinder.SetWallCollidersEnabled (bool wallsEnabled)
Sets the active state of the colliders used for finding safe wall locations.
Parameters
wallsEnabled
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestCollidersDisabled(), CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestCollidersEnabled(), and CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.ResetSceneUnderstanding().
ToggleCellVisibility()
void CrypticCabinet.SceneManagement.WallSpaceFinder.ToggleCellVisibility ()
Toggles the debug cells if the debug material was provided.
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.ToggleDebugView().
Member Data Documentation
TargetCellSize
float CrypticCabinet.SceneManagement.WallSpaceFinder.TargetCellSize = 0.5f
The target size of the cells. This adjusted to ensure the cells fit the wall perfectly.
Referenced by CrypticCabinet.SceneManagement.WallSpaceFinder.AddWall().
The documentation for this class was generated from the following file:
WallSpaceFinder.cs