Cryptic Cabinet: CrypticCabinet.Utils.OculusPlatformUtils Class Reference
CrypticCabinet.Utils.OculusPlatformUtils Class Reference
Utility class to configure the Oculus platform.
Static Public Member Functions
static async Task< bool > InitializeOculusPlatformSDK ()
Initializes the Oculus Core, checks entitlements, retrieves logged user.
static async Task< User > GetLoggedInUser ()
Returns the logged in Oculus user.
static ulong GetUserDeviceGeneratedUid ()
Get the generated unique id of the user device. This will change on every session.
Static Public Attributes
static UnityEvent OnOculusPlatformSDKInitialized = new()
static UnityEvent OnOculusCoreInitializationFailed = new()
static UnityEvent OnEntitlementCheckFailed = new()
static UnityEvent< User > OnOculusUserLoginSuccess = new()
Detailed Description
Utility class to configure the Oculus platform.
Member Function Documentation
GetLoggedInUser()
static async Task< User > CrypticCabinet.Utils.OculusPlatformUtils.GetLoggedInUser () static
Returns the logged in Oculus user.
Returns
The Oculus user currently using the app and logged in.
GetUserDeviceGeneratedUid()
static ulong CrypticCabinet.Utils.OculusPlatformUtils.GetUserDeviceGeneratedUid () static
Get the generated unique id of the user device. This will change on every session.
Returns
generated unique id as a ulong
InitializeOculusPlatformSDK()
static async Task< bool > CrypticCabinet.Utils.OculusPlatformUtils.InitializeOculusPlatformSDK () static
Initializes the Oculus Core, checks entitlements, retrieves logged user.
Returns
True if no error occurs during initialization.
References CrypticCabinet.Utils.OculusPlatformUtils.OnEntitlementCheckFailed, and CrypticCabinet.Utils.OculusPlatformUtils.OnOculusPlatformSDKInitialized.
Referenced by CrypticCabinet.AppStartup.Awake().
Member Data Documentation
OnEntitlementCheckFailed
UnityEvent CrypticCabinet.Utils.OculusPlatformUtils.OnEntitlementCheckFailed = new() static
Referenced by CrypticCabinet.AppStartup.Awake(), CrypticCabinet.Utils.OculusPlatformUtils.InitializeOculusPlatformSDK(), and CrypticCabinet.AppStartup.OnDestroy().
OnOculusCoreInitializationFailed
UnityEvent CrypticCabinet.Utils.OculusPlatformUtils.OnOculusCoreInitializationFailed = new() static
Referenced by CrypticCabinet.AppStartup.Awake(), and CrypticCabinet.AppStartup.OnDestroy().
OnOculusPlatformSDKInitialized
UnityEvent CrypticCabinet.Utils.OculusPlatformUtils.OnOculusPlatformSDKInitialized = new() static
Referenced by CrypticCabinet.AppStartup.Awake(), CrypticCabinet.Utils.OculusPlatformUtils.InitializeOculusPlatformSDK(), and CrypticCabinet.AppStartup.OnDestroy().
OnOculusUserLoginSuccess
UnityEvent<User> CrypticCabinet.Utils.OculusPlatformUtils.OnOculusUserLoginSuccess = new() static
Referenced by CrypticCabinet.AppStartup.Awake(), and CrypticCabinet.AppStartup.OnDestroy().
The documentation for this class was generated from the following file:
OculusPlatformUtils.cs