Cryptic Cabinet: CrypticCabinet.GameManagement.GamePhase Class Reference
CrypticCabinet.GameManagement.GamePhase Class Reference
Represents a game phase for the gameplay.
Public Member Functions
void Initialize ()
void Deinitialize ()
Protected Member Functions
virtual void InitializeInternal ()
virtual void DeinitializeInternal ()
Detailed Description
Represents a game phase for the gameplay.
Member Function Documentation
Deinitialize()
void CrypticCabinet.GameManagement.GamePhase.Deinitialize ()
References CrypticCabinet.GameManagement.GamePhase.DeinitializeInternal().
DeinitializeInternal()
virtual void CrypticCabinet.GameManagement.GamePhase.DeinitializeInternal () protected virtual
Reimplemented in CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase, CrypticCabinet.GameManagement.Timeline.TimelineGamePhase, and CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.
Referenced by CrypticCabinet.GameManagement.GamePhase.Deinitialize().
Initialize()
void CrypticCabinet.GameManagement.GamePhase.Initialize ()
References CrypticCabinet.GameManagement.GamePhase.InitializeInternal().
InitializeInternal()
virtual void CrypticCabinet.GameManagement.GamePhase.InitializeInternal () protected virtual
Reimplemented in CrypticCabinet.GameManagement.Puzzles.SandPuzzleGamePhase, CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase, CrypticCabinet.GameManagement.Timeline.TimelineGamePhase, and CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.
Referenced by CrypticCabinet.GameManagement.GamePhase.Initialize().
The documentation for this class was generated from the following file:
GamePhase.cs