Cryptic Cabinet: CrypticCabinet.Utils.NetworkedSnappedObject Class Reference
CrypticCabinet.Utils.NetworkedSnappedObject Class Reference
Describes a networked snappable object for all users in a session.
Public Member Functions
override void Spawned ()
void Hover (SnapInteractable zone)
void Unhover (SnapInteractable zone)
void Snap (SnapInteractable zone)
void Unsnap (SnapInteractable zone)
void ClearSelectionOverrides ()
Properties
Guid SnapId [get, set]
bool RemoteAdd [get]
bool RemoteRemove [get]
bool RemoteSelectAdd [get]
bool RemoteSelectRemove [get]
Detailed Description
Describes a networked snappable object for all users in a session.
Member Function Documentation
ClearSelectionOverrides()
void CrypticCabinet.Utils.NetworkedSnappedObject.ClearSelectionOverrides ()
Referenced by CrypticCabinet.Utils.NetworkedSnappedObject.Unhover(), and CrypticCabinet.Utils.NetworkedSnappedObject.Unsnap().
Hover()
void CrypticCabinet.Utils.NetworkedSnappedObject.Hover (SnapInteractable zone)
References CrypticCabinet.Utils.NetworkedSnappedObject.RemoteAdd.
Snap()
void CrypticCabinet.Utils.NetworkedSnappedObject.Snap (SnapInteractable zone)
References CrypticCabinet.Utils.NetworkedSnappedObject.RemoteSelectAdd.
Spawned()
override void CrypticCabinet.Utils.NetworkedSnappedObject.Spawned ()
References CrypticCabinet.Utils.NetworkedSnappedObject.SnapId.
Unhover()
void CrypticCabinet.Utils.NetworkedSnappedObject.Unhover (SnapInteractable zone)
References CrypticCabinet.Utils.NetworkedSnappedObject.ClearSelectionOverrides(), and CrypticCabinet.Utils.NetworkedSnappedObject.RemoteRemove.
Unsnap()
void CrypticCabinet.Utils.NetworkedSnappedObject.Unsnap (SnapInteractable zone)
References CrypticCabinet.Utils.NetworkedSnappedObject.ClearSelectionOverrides(), and CrypticCabinet.Utils.NetworkedSnappedObject.RemoteSelectRemove.
Property Documentation
RemoteAdd
bool CrypticCabinet.Utils.NetworkedSnappedObject.RemoteAdd get
Referenced by CrypticCabinet.Utils.NetworkedSnappedObject.Hover().
RemoteRemove
bool CrypticCabinet.Utils.NetworkedSnappedObject.RemoteRemove get
Referenced by CrypticCabinet.Utils.NetworkedSnappedObject.Unhover().
RemoteSelectAdd
bool CrypticCabinet.Utils.NetworkedSnappedObject.RemoteSelectAdd get
Referenced by CrypticCabinet.Utils.NetworkedSnappedObject.Snap().
RemoteSelectRemove
bool CrypticCabinet.Utils.NetworkedSnappedObject.RemoteSelectRemove get
Referenced by CrypticCabinet.Utils.NetworkedSnappedObject.Unsnap().
SnapId
Guid CrypticCabinet.Utils.NetworkedSnappedObject.SnapId get set
Referenced by CrypticCabinet.Utils.NetworkedSnappedObject.Spawned().
The documentation for this class was generated from the following file:
NetworkedSnappedObject.cs