Cryptic Cabinet: CrypticCabinet.UI.Modal.MultiplayerMenu Class Reference
CrypticCabinet.UI.Modal.MultiplayerMenu Class Reference
Handles the logic for a generic Multiplayer Menu UI.
Public Member Functions
void Initialize (Action< string > hostAction, Action< string > joinAction, string defaultRoomName=null)
Initialize the callbacks for the click of the buttons, and optionally set the default room name.
void OnHostClicked ()
Execute the callback associated to the Host button click.
void OnJoinClicked ()
Execute the callback associated to the Join button click.
void OnBackClicked ()
Detailed Description
Handles the logic for a generic Multiplayer Menu UI.
Member Function Documentation
Initialize()
void CrypticCabinet.UI.Modal.MultiplayerMenu.Initialize (Action< string > hostAction, Action< string > joinAction, string defaultRoomName = null)
Initialize the callbacks for the click of the buttons, and optionally set the default room name.
Parameters
hostAction The callback to run when the Host button is clicked.
joinAction The callback to run when the Join button is clicked.
defaultRoomName [Optional] the default room name to join.
Referenced by CrypticCabinet.UI.UISystem.ShowNetworkSelectionMenu().
OnBackClicked()
void CrypticCabinet.UI.Modal.MultiplayerMenu.OnBackClicked ()
References CrypticCabinet.UI.UISystem.HideNetworkSelectionMenu(), and CrypticCabinet.UI.UISystem.ShowMainMenu().
OnHostClicked()
void CrypticCabinet.UI.Modal.MultiplayerMenu.OnHostClicked ()
Execute the callback associated to the Host button click.
References CrypticCabinet.Photon.Utils.RoomNameGenerator.GenerateRoom().
OnJoinClicked()
void CrypticCabinet.UI.Modal.MultiplayerMenu.OnJoinClicked ()
Execute the callback associated to the Join button click.
References CrypticCabinet.UI.UISystem.HideNetworkSelectionMenu(), CrypticCabinet.UI.UISystem.ShowMessage(), and CrypticCabinet.Photon.PhotonConnector.ShowNetworkSelectionMenu().
The documentation for this class was generated from the following file:
MultiplayerMenu.cs