Cryptic Cabinet: CrypticCabinet.Editor.AppBuilder Class Reference
CrypticCabinet.Editor.AppBuilder Class Reference
Small class for build the application. Currently depends on the correct scenes being in the build settings.
Static Public Member Functions
static void ReleaseBuild ()
In editor build option for a release build, using the default debug signing.
static void DebugBuild ()
Editor debug build that allows for script debugging.
static void BuildWithCommandLineArgs ()
Parses custom command line variables to set keystore and version number information. -keystorename Path to the keystore file -keystorepass Password for the keystore -keyaliasname Select keystore alias name -keyaliaspass Alias password -bundleversioncode The Android version code -bundlenumber App version number.
static void PipelineBuildWithKeystore (string outputPath, string keystorePath, string keystorePass, string keyaliasName, string keyaliasPass)
Builds a release build using the provided keystore credentials.
static void PipelineBuild (string outputPath)
Builds the application using the signing that is set up in the project into the target folder.
Detailed Description
Small class for build the application. Currently depends on the correct scenes being in the build settings.
Member Function Documentation
BuildWithCommandLineArgs()
static void CrypticCabinet.Editor.AppBuilder.BuildWithCommandLineArgs () static
Parses custom command line variables to set keystore and version number information. -keystorename Path to the keystore file -keystorepass Password for the keystore -keyaliasname Select keystore alias name -keyaliaspass Alias password -bundleversioncode The Android version code -bundlenumber App version number.
References CrypticCabinet.Editor.AppBuilder.ReleaseBuild().
DebugBuild()
static void CrypticCabinet.Editor.AppBuilder.DebugBuild () static
Editor debug build that allows for script debugging.
PipelineBuild()
static void CrypticCabinet.Editor.AppBuilder.PipelineBuild (string outputPath) static
Builds the application using the signing that is set up in the project into the target folder.
Parameters
outputPath Output build file, this should include the .apk file extension.
Referenced by CrypticCabinet.Editor.AppBuilder.PipelineBuildWithKeystore().
PipelineBuildWithKeystore()
static void CrypticCabinet.Editor.AppBuilder.PipelineBuildWithKeystore (string outputPath, string keystorePath, string keystorePass, string keyaliasName, string keyaliasPass) static
Builds a release build using the provided keystore credentials.
Parameters
outputPath Output build file, this should include the .apk file extension.
keystorePath Path to the keystore.
keystorePass Keystore password.
keyaliasName Alias in keystore to be used.
keyaliasPass Alias password.
References CrypticCabinet.Editor.AppBuilder.PipelineBuild().
ReleaseBuild()
static void CrypticCabinet.Editor.AppBuilder.ReleaseBuild () static
In editor build option for a release build, using the default debug signing.
Referenced by CrypticCabinet.Editor.AppBuilder.BuildWithCommandLineArgs().
The documentation for this class was generated from the following file:
AppBuilder.cs