Cryptic Cabinet: CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase Class Reference
CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase Class Reference
Represent the game phase that configures the placement of the virtual objects into the real room.
Protected Member Functions
override void InitializeInternal ()
override void DeinitializeInternal ()
Additional Inherited Members
Public Member Functions inherited from CrypticCabinet.GameManagement.GamePhase
void Initialize ()
void Deinitialize ()
Detailed Description
Represent the game phase that configures the placement of the virtual objects into the real room.
Member Function Documentation
DeinitializeInternal()
override void CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase.DeinitializeInternal () protected virtual
Reimplemented from CrypticCabinet.GameManagement.GamePhase.
References CrypticCabinet.Utils.ObjectPlacementManager.CleanUp().
InitializeInternal()
override void CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase.InitializeInternal () protected virtual
Reimplemented from CrypticCabinet.GameManagement.GamePhase.
References CrypticCabinet.UI.UISystem.HideAll(), CrypticCabinet.Photon.PhotonConnector.IsMasterClient(), and CrypticCabinet.GameManagement.GameManager.NextGameplayPhase().
The documentation for this class was generated from the following file:
ObjectSpawningLogicPhase.cs