Cryptic Cabinet: CrypticCabinet.UI.Modal.ModalMessageWithButtons Class Reference
CrypticCabinet.UI.Modal.ModalMessageWithButtons Class Reference
A convenient modal window with two customizable buttons that can show a text message to the user and provide actions on button press.
Public Member Functions
void Initialize (string message, string button1Text, Action button1Action, string button2Text, Action button2Action, Action onAnyButtonPressed)
Call this to initialize the buttons for this modal. If the button text is set to String.Empty, the button will not show in the modal.
void Uninitialize ()
Call this function to clear all fields of this modal.
void OnButton1Clicked ()
Run the callback associated to the button 1 click.
void OnButton2Clicked ()
Run the callback associated to the button 2 click.
Public Member Functions inherited from CrypticCabinet.UI.Modal.ModalMessage
void SetText (string text)
Detailed Description
A convenient modal window with two customizable buttons that can show a text message to the user and provide actions on button press.
Member Function Documentation
Initialize()
void CrypticCabinet.UI.Modal.ModalMessageWithButtons.Initialize (string message, string button1Text, Action button1Action, string button2Text, Action button2Action, Action onAnyButtonPressed)
Call this to initialize the buttons for this modal. If the button text is set to String.Empty, the button will not show in the modal.
Parameters
message Message to show on this modal.
button1Text Text for button 1
button1Action Action to perform when button 1 is pressed
button2Text Text for button 2
button2Action Action to perform when button 2 is pressed
onAnyButtonPressed Optional action to perform when any of the buttons is pressed
References CrypticCabinet.UI.Modal.ModalMessage.SetText(), and CrypticCabinet.UI.Modal.ModalMessageWithButtons.Uninitialize().
OnButton1Clicked()
void CrypticCabinet.UI.Modal.ModalMessageWithButtons.OnButton1Clicked ()
Run the callback associated to the button 1 click.
OnButton2Clicked()
void CrypticCabinet.UI.Modal.ModalMessageWithButtons.OnButton2Clicked ()
Run the callback associated to the button 2 click.
Uninitialize()
void CrypticCabinet.UI.Modal.ModalMessageWithButtons.Uninitialize ()
Call this function to clear all fields of this modal.
References CrypticCabinet.UI.Modal.ModalMessage.SetText().
Referenced by CrypticCabinet.UI.Modal.ModalMessageWithButtons.Initialize().
The documentation for this class was generated from the following file:
ModalMessageWithButtons.cs