Cryptic Cabinet: CrypticCabinet.Puzzles.SandPuzzle.Rope Class Reference
CrypticCabinet.Puzzles.SandPuzzle.Rope Class Reference
Describes the rope for the sand puzzle. Based on: https://github.com/GaryMcWhorter/Verlet-Chain-Unity.
Public Member Functions
override void Spawned ()
void Reset ()
Vector3 NearestPointOnRope (Vector3 queryPoint)
int GrabRopeAtPoint (Vector3 queryPoint)
void ReleaseRope (int index)
void UpdateGrabbedRope (int index, Vector3 pos)
Properties
bool AddWeightToEnd [get, set]
Detailed Description
Describes the rope for the sand puzzle. Based on: https://github.com/GaryMcWhorter/Verlet-Chain-Unity.
Member Function Documentation
GrabRopeAtPoint()
int CrypticCabinet.Puzzles.SandPuzzle.Rope.GrabRopeAtPoint (Vector3 queryPoint)
References CrypticCabinet.Utils.MathsUtils.NearestPointOnLineSegment().
Referenced by CrypticCabinet.Puzzles.SandPuzzle.RopeGrabPoint.Grabbed().
NearestPointOnRope()
Vector3 CrypticCabinet.Puzzles.SandPuzzle.Rope.NearestPointOnRope (Vector3 queryPoint)
References CrypticCabinet.Utils.MathsUtils.NearestPointOnLineSegment().
ReleaseRope()
void CrypticCabinet.Puzzles.SandPuzzle.Rope.ReleaseRope (int index)
Referenced by CrypticCabinet.Puzzles.SandPuzzle.RopeGrabPoint.Release().
Reset()
void CrypticCabinet.Puzzles.SandPuzzle.Rope.Reset ()
Referenced by CrypticCabinet.Puzzles.SandPuzzle.Rope.Spawned().
Spawned()
override void CrypticCabinet.Puzzles.SandPuzzle.Rope.Spawned ()
References CrypticCabinet.Puzzles.SandPuzzle.Rope.Reset().
UpdateGrabbedRope()
void CrypticCabinet.Puzzles.SandPuzzle.Rope.UpdateGrabbedRope (int index, Vector3 pos)
Property Documentation
AddWeightToEnd
bool CrypticCabinet.Puzzles.SandPuzzle.Rope.AddWeightToEnd get set
The documentation for this class was generated from the following file:
Rope.cs