Cryptic Cabinet: CrypticCabinet.Colocation.ColocationDriverNetObj Class Reference
CrypticCabinet.Colocation.ColocationDriverNetObj Class Reference
Manages the complete workflow to ensure that all existing and new users will be colocated correctly into the room.
Public Member Functions
void SetPlayerIdDictionary (PhotonPlayerIDDictionary idDictionary)
override void Spawned ()
IEnumerator RetryColocation ()
void OnPlayerJoined (NetworkRunner runner, PlayerRef player)
void OnPlayerLeft (NetworkRunner runner, PlayerRef player)
void OnInput (NetworkRunner runner, NetworkInput input)
void OnInputMissing (NetworkRunner runner, PlayerRef player, NetworkInput input)
void OnShutdown (NetworkRunner runner, ShutdownReason shutdownReason)
void OnConnectedToServer (NetworkRunner runner)
void OnDisconnectedFromServer (NetworkRunner runner)
void OnConnectRequest (NetworkRunner runner, NetworkRunnerCallbackArgs.ConnectRequest request, byte[] token)
void OnConnectFailed (NetworkRunner runner, NetAddress remoteAddress, NetConnectFailedReason reason)
void OnUserSimulationMessage (NetworkRunner runner, SimulationMessagePtr message)
void OnSessionListUpdated (NetworkRunner runner, List< SessionInfo > sessionList)
void OnCustomAuthenticationResponse (NetworkRunner runner, Dictionary< string, object > data)
void OnHostMigration (NetworkRunner runner, HostMigrationToken hostMigrationToken)
void OnReliableDataReceived (NetworkRunner runner, PlayerRef player, ArraySegment< byte > data)
void OnSceneLoadDone (NetworkRunner runner)
void OnSceneLoadStart (NetworkRunner runner)
Static Public Attributes
static Action< bool > OnColocationCompletedCallback
Callback for when the colocation process completes. If succeeded, the callback will be passed a true, otherwise a false.
static bool SkipColocation
If set to true, the colocation process will be skipped. False otherwise.
static Action OnColocationSkippedCallback
Callback for when the colocation process is skipped.
Properties
static ColocationDriverNetObj Instance [get]
PhotonPlayerIDDictionary PlayerIDDictionary [get]
Keeps track of the list of players IDs connected to the same game session.
Detailed Description
Manages the complete workflow to ensure that all existing and new users will be colocated correctly into the room.
Member Function Documentation
OnConnectedToServer()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnConnectedToServer (NetworkRunner runner)
OnConnectFailed()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnConnectFailed (NetworkRunner runner, NetAddress remoteAddress, NetConnectFailedReason reason)
OnConnectRequest()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnConnectRequest (NetworkRunner runner, NetworkRunnerCallbackArgs::ConnectRequest request, byte[] token)
OnCustomAuthenticationResponse()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnCustomAuthenticationResponse (NetworkRunner runner, Dictionary< string, object > data)
OnDisconnectedFromServer()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnDisconnectedFromServer (NetworkRunner runner)
OnHostMigration()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnHostMigration (NetworkRunner runner, HostMigrationToken hostMigrationToken)
OnInput()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnInput (NetworkRunner runner, NetworkInput input)
OnInputMissing()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnInputMissing (NetworkRunner runner, PlayerRef player, NetworkInput input)
OnPlayerJoined()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnPlayerJoined (NetworkRunner runner, PlayerRef player)
OnPlayerLeft()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnPlayerLeft (NetworkRunner runner, PlayerRef player)
References CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.GetOculusId(), CrypticCabinet.Colocation.ColocationDriverNetObj.PlayerIDDictionary, and CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.RemoveUsingNetworkId().
OnReliableDataReceived()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnReliableDataReceived (NetworkRunner runner, PlayerRef player, ArraySegment< byte > data)
OnSceneLoadDone()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnSceneLoadDone (NetworkRunner runner)
OnSceneLoadStart()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnSceneLoadStart (NetworkRunner runner)
OnSessionListUpdated()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnSessionListUpdated (NetworkRunner runner, List< SessionInfo > sessionList)
OnShutdown()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnShutdown (NetworkRunner runner, ShutdownReason shutdownReason)
OnUserSimulationMessage()
void CrypticCabinet.Colocation.ColocationDriverNetObj.OnUserSimulationMessage (NetworkRunner runner, SimulationMessagePtr message)
RetryColocation()
IEnumerator CrypticCabinet.Colocation.ColocationDriverNetObj.RetryColocation ()
References CrypticCabinet.GameManagement.GameManager.RestartGameplay().
SetPlayerIdDictionary()
void CrypticCabinet.Colocation.ColocationDriverNetObj.SetPlayerIdDictionary (PhotonPlayerIDDictionary idDictionary)
Referenced by CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.Spawned().
Spawned()
override void CrypticCabinet.Colocation.ColocationDriverNetObj.Spawned ()
Member Data Documentation
OnColocationCompletedCallback
Action<bool> CrypticCabinet.Colocation.ColocationDriverNetObj.OnColocationCompletedCallback static
Callback for when the colocation process completes. If succeeded, the callback will be passed a true, otherwise a false.
OnColocationSkippedCallback
Action CrypticCabinet.Colocation.ColocationDriverNetObj.OnColocationSkippedCallback static
Callback for when the colocation process is skipped.
SkipColocation
bool CrypticCabinet.Colocation.ColocationDriverNetObj.SkipColocation static
If set to true, the colocation process will be skipped. False otherwise.
Property Documentation
Instance
ColocationDriverNetObj CrypticCabinet.Colocation.ColocationDriverNetObj.Instance static get
Referenced by CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.Spawned(), and CrypticCabinet.Player.CrypticCabinetPlayer.Spawned().
PlayerIDDictionary
PhotonPlayerIDDictionary CrypticCabinet.Colocation.ColocationDriverNetObj.PlayerIDDictionary get
Keeps track of the list of players IDs connected to the same game session.
Referenced by CrypticCabinet.Colocation.ColocationDriverNetObj.OnPlayerLeft(), and CrypticCabinet.Player.CrypticCabinetPlayer.Spawned().
The documentation for this class was generated from the following file:
ColocationDriverNetObj.cs