Cryptic Cabinet: CrypticCabinet.Passthrough.PassthroughConfigurator Class Reference
CrypticCabinet.Passthrough.PassthroughConfigurator Class Reference
Allows to change settings of a specified passthrough layer on demand. It can propagate the change to all players using RPC.
Public Member Functions
void Awake ()
void ResetPassthrough ()
void SetOpacity (float opacity, bool propagateToAllClients)
void SetContrast (float contrast, bool propagateToAllClients)
void SetBrightness (float brightness, bool propagateToAllClients)
void SetSaturation (float saturation, bool propagateToAllClients)
void SetLut (ELutId lutID, float targetBlend, bool propagateToAllClients)
Properties
static PassthroughConfigurator Instance [get]
Detailed Description
Allows to change settings of a specified passthrough layer on demand. It can propagate the change to all players using RPC.
Member Function Documentation
Awake()
void CrypticCabinet.Passthrough.PassthroughConfigurator.Awake ()
References CrypticCabinet.Passthrough.PassthroughConfigurator.Instance.
ResetPassthrough()
void CrypticCabinet.Passthrough.PassthroughConfigurator.ResetPassthrough ()
SetBrightness()
void CrypticCabinet.Passthrough.PassthroughConfigurator.SetBrightness (float brightness, bool propagateToAllClients)
Referenced by CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughBrightness().
SetContrast()
void CrypticCabinet.Passthrough.PassthroughConfigurator.SetContrast (float contrast, bool propagateToAllClients)
Referenced by CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughContrast().
SetLut()
void CrypticCabinet.Passthrough.PassthroughConfigurator.SetLut (ELutId lutID, float targetBlend, bool propagateToAllClients)
SetOpacity()
void CrypticCabinet.Passthrough.PassthroughConfigurator.SetOpacity (float opacity, bool propagateToAllClients)
Referenced by CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughOpacity().
SetSaturation()
void CrypticCabinet.Passthrough.PassthroughConfigurator.SetSaturation (float saturation, bool propagateToAllClients)
Referenced by CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughSaturation().
Property Documentation
Instance
PassthroughConfigurator CrypticCabinet.Passthrough.PassthroughConfigurator.Instance static get
Referenced by CrypticCabinet.Passthrough.PassthroughConfigurator.Awake(), CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughBrightness(), CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughContrast(), CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughOpacity(), and CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughSaturation().
The documentation for this class was generated from the following file:
PassthroughConfigurator.cs