Cryptic Cabinet: CrypticCabinet.IntroOutro.ActThreeMultiUserManager Class Reference
CrypticCabinet.IntroOutro.ActThreeMultiUserManager Class Reference
Script for the Outro timeline animation control (Act3). Triggers the next timeline phase for all users in a session when the note has been grabbed. On outro timeline completed, it disconnects all guest users, shows credits, and restarts the gameplay.
Public Member Functions
void NoteGrabbed ()
void OnActThreeComplete ()
Detailed Description
Script for the Outro timeline animation control (Act3). Triggers the next timeline phase for all users in a session when the note has been grabbed. On outro timeline completed, it disconnects all guest users, shows credits, and restarts the gameplay.
Member Function Documentation
NoteGrabbed()
void CrypticCabinet.IntroOutro.ActThreeMultiUserManager.NoteGrabbed ()
OnActThreeComplete()
void CrypticCabinet.IntroOutro.ActThreeMultiUserManager.OnActThreeComplete ()
References CrypticCabinet.UI.UISystem.HideAll(), CrypticCabinet.Photon.PhotonConnector.HostDisconnectAllFromRoom(), and CrypticCabinet.UI.UISystem.ShowCredits().
The documentation for this class was generated from the following file:
ActThreeMultiUserManager.cs