Cryptic Cabinet: CrypticCabinet.Photon.PhotonConnector Class Reference
CrypticCabinet.Photon.PhotonConnector Class Reference
Manages network connection between the App and the Photon Fusion cloud services. When in a multiplayer session, it is possible to connect as the main player responsible for the scene configuration (Host), or as guest with colocation (Join).
Public Member Functions
void StartSinglePlayerSession ()
Handles single player flow: the player is the only one in the game session, and none else can join. The room name is randomly generated.
void StartMultiplayerSession ()
Handles multiplayer flow: the UI to choose Host or Guest is shown. Host shows a randomly generated 6 digit room name, which can be communicated to guests. Guests will be able to specify the desired room name and join.
async Task Shutdown ()
Shutdown the previous runner and destroy it.
async Task DisconnectFromRoom ()
Disconnects the current player from the active room. Note: this can also be triggered via editor using the context menu.
void ShowNetworkSelectionMenu ()
bool IsMasterClient ()
Checks if the local player is Host (multiplayer) or the main player of a single player session.
void HostDisconnectAllFromRoom ()
Disconnects all the guests of the current room, destroying the current game session. This should be called when the Host disconnects from a game, so that all remaining guest users will not be stuck inside it.
void HostAllowGuests ()
Allows new Guest users to join the current game session (if any).
void HostForbidGuests ()
Forbids new Guest users from joining the current game session (if any).
void GuestLeaveLobby ()
Call this function if the Guest wants to leave the lobby.
void OnPlayerJoined (NetworkRunner runner, PlayerRef player)
async void OnPlayerLeft (NetworkRunner runner, PlayerRef player)
void OnInput (NetworkRunner runner, NetworkInput input)
void OnInputMissing (NetworkRunner runner, PlayerRef player, NetworkInput input)
void OnShutdown (NetworkRunner runner, ShutdownReason shutdownReason)
void OnConnectedToServer (NetworkRunner runner)
void OnDisconnectedFromServer (NetworkRunner runner)
void OnConnectRequest (NetworkRunner runner, NetworkRunnerCallbackArgs.ConnectRequest request, byte[] token)
void OnConnectFailed (NetworkRunner runner, NetAddress remoteAddress, NetConnectFailedReason reason)
void OnUserSimulationMessage (NetworkRunner runner, SimulationMessagePtr message)
void OnSessionListUpdated (NetworkRunner runner, List< SessionInfo > sessionList)
void OnCustomAuthenticationResponse (NetworkRunner runner, Dictionary< string, object > data)
void OnHostMigration (NetworkRunner runner, HostMigrationToken hostMigrationToken)
void OnReliableDataReceived (NetworkRunner runner, PlayerRef player, ArraySegment< byte > data)
void OnSceneLoadDone (NetworkRunner runner)
void OnSceneLoadStart (NetworkRunner runner)
Public Attributes
UnityEvent OnHostMigrationOccured
Occurs when a Host has changed and a new Runner needs to replace the old one.
Properties
bool JoinedActiveGameSession [get]
NetworkRunner Runner [get]
The Runner that handles all communication between this App and Photon Fusion servers.
bool IsMultiplayerSession [get]
True if the current session is multiplayer. False if the current session is single player.
Detailed Description
Manages network connection between the App and the Photon Fusion cloud services. When in a multiplayer session, it is possible to connect as the main player responsible for the scene configuration (Host), or as guest with colocation (Join).
Member Function Documentation
DisconnectFromRoom()
async Task CrypticCabinet.Photon.PhotonConnector.DisconnectFromRoom ()
Disconnects the current player from the active room. Note: this can also be triggered via editor using the context menu.
References CrypticCabinet.Photon.PhotonConnector.JoinedActiveGameSession, and CrypticCabinet.Photon.PhotonConnector.Runner.
Referenced by CrypticCabinet.UI.Modal.InGameMenu.QuitToMainMenu().
GuestLeaveLobby()
void CrypticCabinet.Photon.PhotonConnector.GuestLeaveLobby ()
Call this function if the Guest wants to leave the lobby.
References CrypticCabinet.Photon.PhotonConnector.JoinedActiveGameSession, and CrypticCabinet.Photon.PhotonConnector.Runner.
Referenced by CrypticCabinet.Photon.PhotonConnector.OnSessionListUpdated().
HostAllowGuests()
void CrypticCabinet.Photon.PhotonConnector.HostAllowGuests ()
Allows new Guest users to join the current game session (if any).
Referenced by CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.InitializeInternal().
HostDisconnectAllFromRoom()
void CrypticCabinet.Photon.PhotonConnector.HostDisconnectAllFromRoom ()
Disconnects all the guests of the current room, destroying the current game session. This should be called when the Host disconnects from a game, so that all remaining guest users will not be stuck inside it.
Referenced by CrypticCabinet.IntroOutro.ActThreeMultiUserManager.OnActThreeComplete().
HostForbidGuests()
void CrypticCabinet.Photon.PhotonConnector.HostForbidGuests ()
Forbids new Guest users from joining the current game session (if any).
IsMasterClient()
bool CrypticCabinet.Photon.PhotonConnector.IsMasterClient ()
Checks if the local player is Host (multiplayer) or the main player of a single player session.
Returns
True if the local player is Host in multiplayer, or in single player mode.
References CrypticCabinet.Photon.PhotonConnector.Runner.
Referenced by CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase.InitializeInternal(), CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.InitializeInternal(), CrypticCabinet.Photon.PhotonConnector.OnConnectedToServer(), and CrypticCabinet.Photon.PhotonConnector.OnSessionListUpdated().
OnConnectedToServer()
void CrypticCabinet.Photon.PhotonConnector.OnConnectedToServer (NetworkRunner runner)
References CrypticCabinet.Photon.PhotonConnector.IsMasterClient(), and CrypticCabinet.UI.UISystem.ShowMessage().
OnConnectFailed()
void CrypticCabinet.Photon.PhotonConnector.OnConnectFailed (NetworkRunner runner, NetAddress remoteAddress, NetConnectFailedReason reason)
OnConnectRequest()
void CrypticCabinet.Photon.PhotonConnector.OnConnectRequest (NetworkRunner runner, NetworkRunnerCallbackArgs::ConnectRequest request, byte[] token)
OnCustomAuthenticationResponse()
void CrypticCabinet.Photon.PhotonConnector.OnCustomAuthenticationResponse (NetworkRunner runner, Dictionary< string, object > data)
OnDisconnectedFromServer()
void CrypticCabinet.Photon.PhotonConnector.OnDisconnectedFromServer (NetworkRunner runner)
OnHostMigration()
void CrypticCabinet.Photon.PhotonConnector.OnHostMigration (NetworkRunner runner, HostMigrationToken hostMigrationToken)
OnInput()
void CrypticCabinet.Photon.PhotonConnector.OnInput (NetworkRunner runner, NetworkInput input)
OnInputMissing()
void CrypticCabinet.Photon.PhotonConnector.OnInputMissing (NetworkRunner runner, PlayerRef player, NetworkInput input)
OnPlayerJoined()
void CrypticCabinet.Photon.PhotonConnector.OnPlayerJoined (NetworkRunner runner, PlayerRef player)
OnPlayerLeft()
async void CrypticCabinet.Photon.PhotonConnector.OnPlayerLeft (NetworkRunner runner, PlayerRef player)
OnReliableDataReceived()
void CrypticCabinet.Photon.PhotonConnector.OnReliableDataReceived (NetworkRunner runner, PlayerRef player, ArraySegment< byte > data)
OnSceneLoadDone()
void CrypticCabinet.Photon.PhotonConnector.OnSceneLoadDone (NetworkRunner runner)
References CrypticCabinet.Photon.PhotonConnector.IsMultiplayerSession, and CrypticCabinet.Photon.PhotonConnector.Runner.
OnSceneLoadStart()
void CrypticCabinet.Photon.PhotonConnector.OnSceneLoadStart (NetworkRunner runner)
OnSessionListUpdated()
void CrypticCabinet.Photon.PhotonConnector.OnSessionListUpdated (NetworkRunner runner, List< SessionInfo > sessionList)
References CrypticCabinet.Photon.PhotonConnector.GuestLeaveLobby(), CrypticCabinet.Photon.PhotonConnector.IsMasterClient(), CrypticCabinet.UI.UISystem.ShowMessage(), and CrypticCabinet.Photon.PhotonConnector.ShowNetworkSelectionMenu().
OnShutdown()
void CrypticCabinet.Photon.PhotonConnector.OnShutdown (NetworkRunner runner, ShutdownReason shutdownReason)
OnUserSimulationMessage()
void CrypticCabinet.Photon.PhotonConnector.OnUserSimulationMessage (NetworkRunner runner, SimulationMessagePtr message)
ShowNetworkSelectionMenu()
void CrypticCabinet.Photon.PhotonConnector.ShowNetworkSelectionMenu ()
Referenced by CrypticCabinet.UI.Modal.MultiplayerMenu.OnJoinClicked(), CrypticCabinet.Photon.PhotonConnector.OnSessionListUpdated(), and CrypticCabinet.Photon.PhotonConnector.StartMultiplayerSession().
Shutdown()
async Task CrypticCabinet.Photon.PhotonConnector.Shutdown ()
Shutdown the previous runner and destroy it.
References CrypticCabinet.Photon.PhotonConnector.Runner.
Referenced by CrypticCabinet.UI.Modal.Credits.OnBackClicked().
StartMultiplayerSession()
void CrypticCabinet.Photon.PhotonConnector.StartMultiplayerSession ()
Handles multiplayer flow: the UI to choose Host or Guest is shown. Host shows a randomly generated 6 digit room name, which can be communicated to guests. Guests will be able to specify the desired room name and join.
References CrypticCabinet.Photon.PhotonConnector.IsMultiplayerSession, and CrypticCabinet.Photon.PhotonConnector.ShowNetworkSelectionMenu().
Referenced by CrypticCabinet.UI.Modal.MainMenu.OnMultiplayerPressed().
StartSinglePlayerSession()
void CrypticCabinet.Photon.PhotonConnector.StartSinglePlayerSession ()
Handles single player flow: the player is the only one in the game session, and none else can join. The room name is randomly generated.
References CrypticCabinet.Photon.Utils.RoomNameGenerator.GenerateRoom(), and CrypticCabinet.Photon.PhotonConnector.IsMultiplayerSession.
Referenced by CrypticCabinet.UI.Modal.MainMenu.OnSinglePlayerPressed().
Member Data Documentation
OnHostMigrationOccured
UnityEvent CrypticCabinet.Photon.PhotonConnector.OnHostMigrationOccured
Occurs when a Host has changed and a new Runner needs to replace the old one.
Referenced by CrypticCabinet.Player.CrypticCabinetPlayer.OnDestroy().
Property Documentation
IsMultiplayerSession
bool CrypticCabinet.Photon.PhotonConnector.IsMultiplayerSession get
True if the current session is multiplayer. False if the current session is single player.
Referenced by CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.InitializeInternal(), CrypticCabinet.Photon.PhotonConnector.OnSceneLoadDone(), CrypticCabinet.Player.CrypticCabinetPlayer.Spawned(), CrypticCabinet.Photon.PhotonConnector.StartMultiplayerSession(), and CrypticCabinet.Photon.PhotonConnector.StartSinglePlayerSession().
JoinedActiveGameSession
bool CrypticCabinet.Photon.PhotonConnector.JoinedActiveGameSession get
Referenced by CrypticCabinet.Photon.PhotonConnector.DisconnectFromRoom(), and CrypticCabinet.Photon.PhotonConnector.GuestLeaveLobby().
Runner
NetworkRunner CrypticCabinet.Photon.PhotonConnector.Runner get
The Runner that handles all communication between this App and Photon Fusion servers.
Referenced by CrypticCabinet.GameManagement.Timeline.TimelineGamePhase.DeinitializeInternal(), CrypticCabinet.Photon.PhotonConnector.DisconnectFromRoom(), CrypticCabinet.Photon.PhotonConnector.GuestLeaveLobby(), CrypticCabinet.GameManagement.Puzzles.SandPuzzleGamePhase.InitializeInternal(), CrypticCabinet.GameManagement.Timeline.TimelineGamePhase.InitializeInternal(), CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.InitializeInternal(), CrypticCabinet.Photon.PhotonConnector.IsMasterClient(), CrypticCabinet.UI.Modal.Credits.OnBackClicked(), CrypticCabinet.Photon.PhotonConnector.OnSceneLoadDone(), CrypticCabinet.Photon.PhotonConnector.Shutdown(), CrypticCabinet.Puzzles.Cabinet.Spawned(), and CrypticCabinet.GameManagement.GameManager.StartGameplay().
The documentation for this class was generated from the following file:
PhotonConnector.cs