Cryptic Cabinet: CrypticCabinet.SceneManagement.FloorSpaceFinder Class Reference
CrypticCabinet.SceneManagement.FloorSpaceFinder Class Reference
System for finding the space on a floor including functionality to place relative to the wall.
Public Member Functions
bool HasSetUpCompleted ()
void CleanUp ()
void GetFinderTransform (out Matrix4x4 localToWorldMatrix)
void GetFinderSize (out Vector3 worldSize)
bool CheckPhysicsResultIsClear (Collider[] hitColliders, int hitCount)
void BlockPhysicsResult (Collider[] hitColliders, int hitCount)
bool RequestRandomLocation (Vector3 locationToFace, float objectRadius, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked=false, float edgeDistance=-1)
Requests a random floor location that is both a set distance from a floor and and not intersecting with any objects.
bool RequestRandomLocation (Vector3 locationToFace, Vector3 objectDimensions, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked=false)
void GenerateCells ()
Generates the cells over the floor plane. This is done by generating an array of points that are in a grid using the OVRScenePlane.Dimensions field, and then raycast against the floor plane mesh collider to find valid locations.
void RememberDistanceField ()
void ResetDistanceField ()
void SetDebugViewEnabled (bool isVisible)
void ToggleDebugView ()
void SetSearchCollidersActive (bool collidersActive)
void CalculateBlockedArea (Matrix4x4 objectTransform, Vector2 objectSize)
Takes a 2D plane and calculates the blocked area for it.
void CalculateBlockedArea (Matrix4x4 objectTransform, Vector3 objectSize)
Uses the passed in details to workout the areas on the floor that are blocked by the object, updating the the distance field accordingly.
void RequestTrulyRandomLocation (out Vector3 position)
Public Attributes
Material DebugMaterial
Properties
Vector3 FloorCenterPosition [get]
bool IsReadyToGenerate [get]
Detailed Description
System for finding the space on a floor including functionality to place relative to the wall.
Member Function Documentation
BlockPhysicsResult()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.BlockPhysicsResult (Collider[] hitColliders, int hitCount)
Referenced by CrypticCabinet.SceneManagement.FloorSpaceFinder.RequestRandomLocation().
CalculateBlockedArea() [1/2]
void CrypticCabinet.SceneManagement.FloorSpaceFinder.CalculateBlockedArea (Matrix4x4 objectTransform, Vector2 objectSize)
Takes a 2D plane and calculates the blocked area for it.
Parameters
objectTransform Matrix describing the objects position.
objectSize Dimensions of the surface.
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
References CrypticCabinet.SceneManagement.FloorSpaceFinder.CalculateBlockedArea().
Referenced by CrypticCabinet.SceneManagement.FloorSpaceFinder.CalculateBlockedArea(), and CrypticCabinet.SceneManagement.FloorSpaceFinder.GenerateCells().
CalculateBlockedArea() [2/2]
void CrypticCabinet.SceneManagement.FloorSpaceFinder.CalculateBlockedArea (Matrix4x4 objectTransform, Vector3 objectSize)
Uses the passed in details to workout the areas on the floor that are blocked by the object, updating the the distance field accordingly.
Parameters
objectTransform Transform of the potentially blocking object.
objectSize Dimensions of the object.
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
References CrypticCabinet.SceneManagement.FloorSpaceFinder.RememberDistanceField().
CheckPhysicsResultIsClear()
bool CrypticCabinet.SceneManagement.FloorSpaceFinder.CheckPhysicsResultIsClear (Collider[] hitColliders, int hitCount)
Referenced by CrypticCabinet.SceneManagement.FloorSpaceFinder.RequestRandomLocation().
CleanUp()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.CleanUp ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
GenerateCells()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.GenerateCells ()
Generates the cells over the floor plane. This is done by generating an array of points that are in a grid using the OVRScenePlane.Dimensions field, and then raycast against the floor plane mesh collider to find valid locations.
References CrypticCabinet.SceneManagement.FloorSpaceFinder.CalculateBlockedArea(), CrypticCabinet.SceneManagement.FloorSpaceFinder.DebugMaterial, and CrypticCabinet.SceneManagement.FloorSpaceFinder.RememberDistanceField().
GetFinderSize()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.GetFinderSize (out Vector3 worldSize)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
GetFinderTransform()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.GetFinderTransform (out Matrix4x4 localToWorldMatrix)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
HasSetUpCompleted()
bool CrypticCabinet.SceneManagement.FloorSpaceFinder.HasSetUpCompleted ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
RememberDistanceField()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.RememberDistanceField ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
References CrypticCabinet.SceneManagement.FloorSpaceFinder.FloorCenterPosition.
Referenced by CrypticCabinet.SceneManagement.FloorSpaceFinder.CalculateBlockedArea(), and CrypticCabinet.SceneManagement.FloorSpaceFinder.GenerateCells().
RequestRandomLocation() [1/2]
bool CrypticCabinet.SceneManagement.FloorSpaceFinder.RequestRandomLocation (Vector3 locationToFace, float objectRadius, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked = false, float edgeDistance = -1)
Requests a random floor location that is both a set distance from a floor and and not intersecting with any objects.
Parameters
locationToFace The location of the user that the spawned object should face.
objectRadius Radius of the object being placed
foundPosition Returns the chosen random location.
markAsBlocked When true, the cell is marked as blocked, otherwise it is unchanged.
edgeDistance The desired distance from the wall, otherwise -1 to ignore.
Returns
Float to if a location was successfully found.
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
References CrypticCabinet.SceneManagement.FloorSpaceFinder.RequestRandomLocation().
Referenced by CrypticCabinet.SceneManagement.FloorSpaceFinder.RequestRandomLocation().
RequestRandomLocation() [2/2]
bool CrypticCabinet.SceneManagement.FloorSpaceFinder.RequestRandomLocation (Vector3 locationToFace, Vector3 objectDimensions, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked = false)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
References CrypticCabinet.SceneManagement.FloorSpaceFinder.BlockPhysicsResult(), and CrypticCabinet.SceneManagement.FloorSpaceFinder.CheckPhysicsResultIsClear().
RequestTrulyRandomLocation()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.RequestTrulyRandomLocation (out Vector3 position)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
ResetDistanceField()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.ResetDistanceField ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
SetDebugViewEnabled()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.SetDebugViewEnabled (bool isVisible)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
SetSearchCollidersActive()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.SetSearchCollidersActive (bool collidersActive)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
ToggleDebugView()
void CrypticCabinet.SceneManagement.FloorSpaceFinder.ToggleDebugView ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
Member Data Documentation
DebugMaterial
Material CrypticCabinet.SceneManagement.FloorSpaceFinder.DebugMaterial
Referenced by CrypticCabinet.SceneManagement.FloorSpaceFinder.GenerateCells().
Property Documentation
FloorCenterPosition
Vector3 CrypticCabinet.SceneManagement.FloorSpaceFinder.FloorCenterPosition get
Referenced by CrypticCabinet.SceneManagement.FloorSpaceFinder.RememberDistanceField().
IsReadyToGenerate
bool CrypticCabinet.SceneManagement.FloorSpaceFinder.IsReadyToGenerate get
The documentation for this class was generated from the following file:
FloorSpaceFinder.cs