Cryptic Cabinet: CrypticCabinet.UI.Modal.MainMenu Class Reference
CrypticCabinet.UI.Modal.MainMenu Class Reference
Handles the logic for the Main Menu UI.
Public Member Functions
void OnSinglePlayerPressed ()
void OnMultiplayerPressed ()
void OnCreditsPressed ()
Public Attributes
UnityEvent OnSinglePlayerPressedAction
UnityEvent OnMultiPlayerPressedAction
UnityEvent OnCreditsPressedAction
Detailed Description
Handles the logic for the Main Menu UI.
Member Function Documentation
OnCreditsPressed()
void CrypticCabinet.UI.Modal.MainMenu.OnCreditsPressed ()
References CrypticCabinet.UI.UISystem.HideMainMenu(), CrypticCabinet.UI.Modal.MainMenu.OnCreditsPressedAction, and CrypticCabinet.UI.UISystem.ShowCredits().
OnMultiplayerPressed()
void CrypticCabinet.UI.Modal.MainMenu.OnMultiplayerPressed ()
References CrypticCabinet.UI.UISystem.HideMainMenu(), CrypticCabinet.UI.Modal.MainMenu.OnMultiPlayerPressedAction, and CrypticCabinet.Photon.PhotonConnector.StartMultiplayerSession().
OnSinglePlayerPressed()
void CrypticCabinet.UI.Modal.MainMenu.OnSinglePlayerPressed ()
References CrypticCabinet.UI.UISystem.HideMainMenu(), CrypticCabinet.UI.Modal.MainMenu.OnSinglePlayerPressedAction, and CrypticCabinet.Photon.PhotonConnector.StartSinglePlayerSession().
Member Data Documentation
OnCreditsPressedAction
UnityEvent CrypticCabinet.UI.Modal.MainMenu.OnCreditsPressedAction
Referenced by CrypticCabinet.UI.Modal.MainMenu.OnCreditsPressed().
OnMultiPlayerPressedAction
UnityEvent CrypticCabinet.UI.Modal.MainMenu.OnMultiPlayerPressedAction
Referenced by CrypticCabinet.UI.Modal.MainMenu.OnMultiplayerPressed().
OnSinglePlayerPressedAction
UnityEvent CrypticCabinet.UI.Modal.MainMenu.OnSinglePlayerPressedAction
Referenced by CrypticCabinet.UI.Modal.MainMenu.OnSinglePlayerPressed().
The documentation for this class was generated from the following file:
MainMenu.cs