Cryptic Cabinet: CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer Class Reference
CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer Class Reference
Central manager for all surface finding, takes in the objects created by the OVRSceneManager and passed the relevant information to the space finding mangers. Once set up also handles moving the debug visual props to the appropriate locations.
Public Member Functions
void ResetHorizontalBlockedAreas ()
bool HasLoadingCompleted ()
void ToggleDebugView ()
Toggles the debug cell visibility.
bool RequestRandomLocation (Vector3 locationToFace, float radius, out Vector3 foundPosition)
bool RequestRandomFloorLocation (Vector3 locationToFace, Vector3 objectDimensions, out Vector3 foundPosition, out Quaternion foundRotation, float edgeDistance=-1)
bool RequestRandomFloorWallLocation (float halfDepth, float width, float height, out Vector3 foundFloorPosition, out Vector3 foundWallPosition, out Quaternion foundWallRotation, Vector2 edgeDistance)
bool RequestRandomDeskLocation (Vector3 locationToFace, float radius, out Vector3 foundPosition)
bool RequestRandomWallLocation (float heightOffFloor, float objectWidth, float objectHeight, Vector2 edgeDistance, bool ignoreSceneBlocked, out Vector3 foundPosition, out Quaternion foundRotation)
void AddWall (MRUKAnchor plane)
Adds wall plane to the wall list.
void AddOpening (MRUKAnchor doorPlane)
Adds a doors and windows to the openings list.
void AddVolumeObject (MRUKAnchor objectVolume)
Adds any object described with a volume such as storage screens and plants.
void AddDesk (MRUKAnchor deskAnchor)
Adds a desk to the general manager, adds a DeskSpaceFinder to the object.
void AddCouch (MRUKAnchor plane)
Stores couch planes to pass to space managers.
void AddFloor (FloorSpaceFinder floorSpaceFinder)
Stores any FloorSpaceFinders.
void RequestTotallyRandomWallLocation (float minHeight, out Vector3 position, out Quaternion rotation)
void RequestTotallyRandomFloorLocation (out Vector3 position)
void RequestTotallyRandomDeskLocation (out Vector3 position)
void RequestCollidersDisabled ()
void RequestCollidersEnabled ()
void ResetSceneUnderstanding ()
void CleanUp ()
Public Attributes
Material DebugMaterial
Debug material passed to WallSpaceFinder
Action OnSceneLoadingFailed
Protected Member Functions
override void OnEnable ()
Set up the MRUK and load scene data.
Detailed Description
Central manager for all surface finding, takes in the objects created by the OVRSceneManager and passed the relevant information to the space finding mangers. Once set up also handles moving the debug visual props to the appropriate locations.
Member Function Documentation
AddCouch()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.AddCouch (MRUKAnchor plane)
Stores couch planes to pass to space managers.
Parameters
plane Plane that describes a couch
AddDesk()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.AddDesk (MRUKAnchor deskAnchor)
Adds a desk to the general manager, adds a DeskSpaceFinder to the object.
Parameters
plane Plane that describes a desk.
AddFloor()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.AddFloor (FloorSpaceFinder floorSpaceFinder)
Stores any FloorSpaceFinders.
Parameters
floorSpaceFinder
References CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.DebugMaterial.
AddOpening()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.AddOpening (MRUKAnchor doorPlane)
Adds a doors and windows to the openings list.
Parameters
doorPlane Plane that describes a door or window.
AddVolumeObject()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.AddVolumeObject (MRUKAnchor objectVolume)
Adds any object described with a volume such as storage screens and plants.
Parameters
objectVolume Object's volume.
AddWall()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.AddWall (MRUKAnchor plane)
Adds wall plane to the wall list.
Parameters
plane Plane that describes a wall.
CleanUp()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.CleanUp ()
References CrypticCabinet.SceneManagement.WallSpaceFinder.CleanUp().
HasLoadingCompleted()
bool CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.HasLoadingCompleted ()
OnEnable()
override void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.OnEnable () protected
Set up the MRUK and load scene data.
RequestCollidersDisabled()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestCollidersDisabled ()
References CrypticCabinet.SceneManagement.WallSpaceFinder.SetWallCollidersEnabled().
RequestCollidersEnabled()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestCollidersEnabled ()
References CrypticCabinet.SceneManagement.WallSpaceFinder.SetWallCollidersEnabled().
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.ToggleDebugView().
RequestRandomDeskLocation()
bool CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestRandomDeskLocation (Vector3 locationToFace, float radius, out Vector3 foundPosition)
RequestRandomFloorLocation()
bool CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestRandomFloorLocation (Vector3 locationToFace, Vector3 objectDimensions, out Vector3 foundPosition, out Quaternion foundRotation, float edgeDistance = -1)
RequestRandomFloorWallLocation()
bool CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestRandomFloorWallLocation (float halfDepth, float width, float height, out Vector3 foundFloorPosition, out Vector3 foundWallPosition, out Quaternion foundWallRotation, Vector2 edgeDistance)
References CrypticCabinet.SceneManagement.WallSpaceFinder.RequestRandomLocationCustomWithFloor().
RequestRandomLocation()
bool CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestRandomLocation (Vector3 locationToFace, float radius, out Vector3 foundPosition)
RequestRandomWallLocation()
bool CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestRandomWallLocation (float heightOffFloor, float objectWidth, float objectHeight, Vector2 edgeDistance, bool ignoreSceneBlocked, out Vector3 foundPosition, out Quaternion foundRotation)
References CrypticCabinet.SceneManagement.WallSpaceFinder.QueryForSafeWallLocation().
RequestTotallyRandomDeskLocation()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestTotallyRandomDeskLocation (out Vector3 position)
RequestTotallyRandomFloorLocation()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestTotallyRandomFloorLocation (out Vector3 position)
RequestTotallyRandomWallLocation()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestTotallyRandomWallLocation (float minHeight, out Vector3 position, out Quaternion rotation)
References CrypticCabinet.SceneManagement.WallSpaceFinder.PickRandomWallCell().
ResetHorizontalBlockedAreas()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.ResetHorizontalBlockedAreas ()
ResetSceneUnderstanding()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.ResetSceneUnderstanding ()
References CrypticCabinet.SceneManagement.WallSpaceFinder.ResetWallPlacements(), and CrypticCabinet.SceneManagement.WallSpaceFinder.SetWallCollidersEnabled().
ToggleDebugView()
void CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.ToggleDebugView ()
Toggles the debug cell visibility.
References CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.RequestCollidersEnabled(), and CrypticCabinet.SceneManagement.WallSpaceFinder.ToggleCellVisibility().
Member Data Documentation
DebugMaterial
Material CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.DebugMaterial
Debug material passed to WallSpaceFinder
Referenced by CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.AddFloor().
OnSceneLoadingFailed
Action CrypticCabinet.SceneManagement.SceneUnderstandingLocationPlacer.OnSceneLoadingFailed
The documentation for this class was generated from the following file:
SceneUnderstandingLocationPlacer.cs