Cryptic Cabinet: CrypticCabinet.Utils.ObjectPlacementVisualiser Class Reference
CrypticCabinet.Utils.ObjectPlacementVisualiser Class Reference
A visualizer to help with the object placement during scene setup. Note: Rigid body necessary to detect trigger events on enter and exit.
Public Member Functions
void Setup (ObjectPlacementManager objectPlacementManager, Vector3 mainPosition, Vector3 wallPos, Quaternion wallRotation)
void Setup (ObjectPlacementManager objectPlacementManager, Vector3 position)
void Setup (ObjectPlacementManager objectPlacementManager, Vector3 position, Quaternion rotation)
void UpdateLocation ()
Properties
float GetRadius [get]
float GetWallObjectHeight [get]
float GetWallObjectWidth [get]
float GetWallObjectVerticalSize [get]
ObjectPlacementManager.LoadableSceneObjects GetObjectType [get]
bool GetFlipFaceDir [get]
Vector2 GetDistanceFromEdge [get]
bool IsOnTheWall [get]
Vector3 GetObjectDimensions [get]
Detailed Description
A visualizer to help with the object placement during scene setup. Note: Rigid body necessary to detect trigger events on enter and exit.
Member Function Documentation
Setup() [1/3]
void CrypticCabinet.Utils.ObjectPlacementVisualiser.Setup (ObjectPlacementManager objectPlacementManager, Vector3 mainPosition, Vector3 wallPos, Quaternion wallRotation)
References CrypticCabinet.Utils.ObjectPlacementVisualiser.Setup().
Referenced by CrypticCabinet.Utils.ObjectPlacementVisualiser.Setup().
Setup() [2/3]
void CrypticCabinet.Utils.ObjectPlacementVisualiser.Setup (ObjectPlacementManager objectPlacementManager, Vector3 position)
Setup() [3/3]
void CrypticCabinet.Utils.ObjectPlacementVisualiser.Setup (ObjectPlacementManager objectPlacementManager, Vector3 position, Quaternion rotation)
UpdateLocation()
void CrypticCabinet.Utils.ObjectPlacementVisualiser.UpdateLocation ()
References CrypticCabinet.Utils.ObjectPlacementManager.UpdatePlacedObject().
Property Documentation
GetDistanceFromEdge
Vector2 CrypticCabinet.Utils.ObjectPlacementVisualiser.GetDistanceFromEdge get
GetFlipFaceDir
bool CrypticCabinet.Utils.ObjectPlacementVisualiser.GetFlipFaceDir get
GetObjectDimensions
Vector3 CrypticCabinet.Utils.ObjectPlacementVisualiser.GetObjectDimensions get
GetObjectType
ObjectPlacementManager.LoadableSceneObjects CrypticCabinet.Utils.ObjectPlacementVisualiser.GetObjectType get
GetRadius
float CrypticCabinet.Utils.ObjectPlacementVisualiser.GetRadius get
GetWallObjectHeight
float CrypticCabinet.Utils.ObjectPlacementVisualiser.GetWallObjectHeight get
GetWallObjectVerticalSize
float CrypticCabinet.Utils.ObjectPlacementVisualiser.GetWallObjectVerticalSize get
GetWallObjectWidth
float CrypticCabinet.Utils.ObjectPlacementVisualiser.GetWallObjectWidth get
IsOnTheWall
bool CrypticCabinet.Utils.ObjectPlacementVisualiser.IsOnTheWall get
The documentation for this class was generated from the following file:
ObjectPlacementVisualiser.cs