Cryptic Cabinet: CrypticCabinet.UI.Modal.InGameMenu Class Reference
CrypticCabinet.UI.Modal.InGameMenu Class Reference
An in-game menu that can be used to exit the game play.
Public Member Functions
async void QuitToMainMenu ()
void ToggleInGameMenu ()
Detailed Description
An in-game menu that can be used to exit the game play.
Member Function Documentation
QuitToMainMenu()
async void CrypticCabinet.UI.Modal.InGameMenu.QuitToMainMenu ()
References CrypticCabinet.Photon.PhotonConnector.DisconnectFromRoom(), CrypticCabinet.UI.UISystem.HideAll(), and CrypticCabinet.Passthrough.PassthroughChanger.SetPassthroughDefaultLut().
ToggleInGameMenu()
void CrypticCabinet.UI.Modal.InGameMenu.ToggleInGameMenu ()
References CrypticCabinet.GameManagement.GameManager.GetCurrentGamePhase(), CrypticCabinet.UI.UISystem.HideInGameMenu(), and CrypticCabinet.UI.UISystem.ShowInGameMenu().
The documentation for this class was generated from the following file:
InGameMenu.cs