Cryptic Cabinet: CrypticCabinet.UI.UISystem Class Reference
CrypticCabinet.UI.UISystem Class Reference
Singleton to control the menus and windows for the game UI.
Public Member Functions
void ShowMessageWithOneButton (string messageText, string button1Text, Action button1Action)
Show message with one customized button. Note: the message automatically disappears when the user presses the button.
void ShowMessage (string text, PendingTasksHandler.PendingAction onHiddenCallback=null, float hideTime=3.0f)
Show text message to the user, without showing any button. Note: To show buttons, use ShowMessageWithOneButton or ShowMessageWithTwoButtons instead.
void ShowNetworkSelectionMenu (Action< string > hostAction, Action< string > joinAction, string defaultRoomName=null)
void HideNetworkSelectionMenu ()
void ShowInGameMenu ()
void HideInGameMenu ()
void ShowMainMenu ()
void HideMainMenu ()
void ShowCredits ()
void HideCredits ()
void HideAll ()
Detailed Description
Singleton to control the menus and windows for the game UI.
Member Function Documentation
HideAll()
void CrypticCabinet.UI.UISystem.HideAll ()
References CrypticCabinet.UI.UISystem.HideInGameMenu(), and CrypticCabinet.UI.UISystem.HideNetworkSelectionMenu().
Referenced by CrypticCabinet.GameManagement.RoomSetup.ObjectSpawningLogicPhase.InitializeInternal(), CrypticCabinet.GameManagement.WaitForGuests.WaitForGuestsPhase.InitializeInternal(), CrypticCabinet.IntroOutro.ActThreeMultiUserManager.OnActThreeComplete(), CrypticCabinet.UI.Modal.InGameMenu.QuitToMainMenu(), CrypticCabinet.UI.UISystem.ShowInGameMenu(), and CrypticCabinet.UI.UISystem.ShowMessage().
HideCredits()
void CrypticCabinet.UI.UISystem.HideCredits ()
HideInGameMenu()
void CrypticCabinet.UI.UISystem.HideInGameMenu ()
Referenced by CrypticCabinet.UI.UISystem.HideAll(), and CrypticCabinet.UI.Modal.InGameMenu.ToggleInGameMenu().
HideMainMenu()
void CrypticCabinet.UI.UISystem.HideMainMenu ()
Referenced by CrypticCabinet.UI.Modal.MainMenu.OnCreditsPressed(), CrypticCabinet.UI.Modal.MainMenu.OnMultiplayerPressed(), and CrypticCabinet.UI.Modal.MainMenu.OnSinglePlayerPressed().
HideNetworkSelectionMenu()
void CrypticCabinet.UI.UISystem.HideNetworkSelectionMenu ()
Referenced by CrypticCabinet.UI.UISystem.HideAll(), CrypticCabinet.UI.Modal.MultiplayerMenu.OnBackClicked(), and CrypticCabinet.UI.Modal.MultiplayerMenu.OnJoinClicked().
ShowCredits()
void CrypticCabinet.UI.UISystem.ShowCredits ()
Referenced by CrypticCabinet.IntroOutro.ActThreeMultiUserManager.OnActThreeComplete(), and CrypticCabinet.UI.Modal.MainMenu.OnCreditsPressed().
ShowInGameMenu()
void CrypticCabinet.UI.UISystem.ShowInGameMenu ()
References CrypticCabinet.UI.UISystem.HideAll().
Referenced by CrypticCabinet.UI.Modal.InGameMenu.ToggleInGameMenu().
ShowMainMenu()
void CrypticCabinet.UI.UISystem.ShowMainMenu ()
References CrypticCabinet.GameManagement.GameManager.GetCurrentGamePhase().
Referenced by CrypticCabinet.UI.Modal.MultiplayerMenu.OnBackClicked().
ShowMessage()
void CrypticCabinet.UI.UISystem.ShowMessage (string text, PendingTasksHandler::PendingAction onHiddenCallback = null, float hideTime = 3::0f)
Show text message to the user, without showing any button. Note: To show buttons, use ShowMessageWithOneButton or ShowMessageWithTwoButtons instead.
Parameters
text The text message to show
onHiddenCallback Optional action to perform once the text message auto-hides
hideTime How long before the message automatically hides. Set hideTime to a negative value to disable auto-hide.
References CrypticCabinet.UI.UISystem.HideAll(), and CrypticCabinet.UI.Modal.ModalMessage.SetText().
Referenced by CrypticCabinet.Photon.PhotonConnector.OnConnectedToServer(), CrypticCabinet.UI.Modal.MultiplayerMenu.OnJoinClicked(), CrypticCabinet.Photon.PhotonConnector.OnSessionListUpdated(), and CrypticCabinet.GameManagement.GameManager.StartGameplay().
ShowMessageWithOneButton()
void CrypticCabinet.UI.UISystem.ShowMessageWithOneButton (string messageText, string button1Text, Action button1Action)
Show message with one customized button. Note: the message automatically disappears when the user presses the button.
Parameters
messageText Text for the message
button1Text Text for the button
button1Action Action performed when the button is pressed
ShowNetworkSelectionMenu()
void CrypticCabinet.UI.UISystem.ShowNetworkSelectionMenu (Action< string > hostAction, Action< string > joinAction, string defaultRoomName = null)
References CrypticCabinet.UI.Modal.MultiplayerMenu.Initialize().
The documentation for this class was generated from the following file:
UISystem.cs