Cryptic Cabinet: CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary Class Reference
CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary Class Reference
A dictionary of oculus IDs, network IDs, and headset IDs. It can be used to keep track of all connected oculus users, their networks, and their headsets. Note: It is possible to have the same oculus ID for different headsets at the same time.
Public Member Functions
override void Spawned ()
void Add (ulong key, int value, Guid headsetGuid)
void Clear ()
ulong? GetOculusId (int networkId)
object GetNetworkId (ulong oculusId)
object GetNetworkId (Guid headsetId)
bool ContainsOculusId (object oculusId)
bool ContainsNetworkId (object networkId)
bool ContainsHeadsetId (Guid headsetId)
void RemoveUsingOculusId (object oculusId)
void RemoveUsingNetworkId (object networkId)
void RemoveUsingHeadsetId (Guid headsetId)
override string ToString ()
Detailed Description
A dictionary of oculus IDs, network IDs, and headset IDs. It can be used to keep track of all connected oculus users, their networks, and their headsets. Note: It is possible to have the same oculus ID for different headsets at the same time.
Member Function Documentation
Add()
void CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.Add (ulong key, int value, Guid headsetGuid)
Clear()
void CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.Clear ()
ContainsHeadsetId()
bool CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.ContainsHeadsetId (Guid headsetId)
ContainsNetworkId()
bool CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.ContainsNetworkId (object networkId)
ContainsOculusId()
bool CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.ContainsOculusId (object oculusId)
GetNetworkId() [1/2]
object CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.GetNetworkId (Guid headsetId)
GetNetworkId() [2/2]
object CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.GetNetworkId (ulong oculusId)
Referenced by CrypticCabinet.Photon.Colocation.PhotonNetworkMessenger.SendMessageUsingHeadsetId(), and CrypticCabinet.Photon.Colocation.PhotonNetworkMessenger.SendMessageUsingOculusId().
GetOculusId()
ulong? CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.GetOculusId (int networkId)
Referenced by CrypticCabinet.Colocation.ColocationDriverNetObj.OnPlayerLeft(), and CrypticCabinet.Player.CrypticCabinetPlayer.Spawned().
RemoveUsingHeadsetId()
void CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.RemoveUsingHeadsetId (Guid headsetId)
RemoveUsingNetworkId()
void CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.RemoveUsingNetworkId (object networkId)
Referenced by CrypticCabinet.Colocation.ColocationDriverNetObj.OnPlayerLeft().
RemoveUsingOculusId()
void CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.RemoveUsingOculusId (object oculusId)
Spawned()
override void CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.Spawned ()
References CrypticCabinet.Colocation.ColocationDriverNetObj.Instance, and CrypticCabinet.Colocation.ColocationDriverNetObj.SetPlayerIdDictionary().
ToString()
override string CrypticCabinet.Photon.Colocation.PhotonPlayerIDDictionary.ToString ()
The documentation for this class was generated from the following file:
PhotonPlayerIDDictionary.cs