Cryptic Cabinet: CrypticCabinet.SceneManagement.DeskSpaceFinder Class Reference
CrypticCabinet.SceneManagement.DeskSpaceFinder Class Reference
Generates a distance field on plane accounting for blocking objects. Includes functionality to return a position on the plane for a given radius.
Public Member Functions
bool HasSetUpCompleted ()
void CleanUp ()
void GetFinderTransform (out Matrix4x4 localToWorldMatrix)
void GetFinderSize (out Vector3 worldSize)
bool RequestRandomLocation (Vector3 locationToFace, float objectRadius, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked=false, float edgeDistance=-1)
bool RequestRandomLocation (Vector3 locationToFace, Vector3 objectDimensions, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked=false)
bool RequestCenterLocation (float radius, out Vector3 foundPosition, bool markAsBlocked=false, float edgeDistance=-1)
Returns a location on the desk for a given radius, if there's no location that can safely place the object returns false.
void RememberDistanceField ()
void ResetDistanceField ()
void SetDebugViewEnabled (bool isVisible)
void ToggleDebugView ()
void SetSearchCollidersActive (bool collidersActive)
void CalculateBlockedArea (Matrix4x4 objectTransform, Vector2 objectSize)
void CalculateBlockedArea (Matrix4x4 objectTransform, Vector3 objectSize)
Recalculates the distance field accounting for a new Scene object. First checks if the new object blocks any cells then recalculates the cell distances.
void GenerateDeskCells (Material debugMaterial)
Generates the cells for the desk surface.
void RequestTrulyRandomLocation (out Vector3 position)
Public Attributes
Vector2 DeskSize
The width and depth of the desk.
Detailed Description
Generates a distance field on plane accounting for blocking objects. Includes functionality to return a position on the plane for a given radius.
Member Function Documentation
CalculateBlockedArea() [1/2]
void CrypticCabinet.SceneManagement.DeskSpaceFinder.CalculateBlockedArea (Matrix4x4 objectTransform, Vector2 objectSize)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
CalculateBlockedArea() [2/2]
void CrypticCabinet.SceneManagement.DeskSpaceFinder.CalculateBlockedArea (Matrix4x4 objectTransform, Vector3 objectSize)
Recalculates the distance field accounting for a new Scene object. First checks if the new object blocks any cells then recalculates the cell distances.
Parameters
objectTransform The transform matrix describing the location of the object.
objectSize The scale of the object.
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
References CrypticCabinet.SceneManagement.DeskSpaceFinder.RememberDistanceField().
CleanUp()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.CleanUp ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
GenerateDeskCells()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.GenerateDeskCells (Material debugMaterial)
Generates the cells for the desk surface.
Parameters
debugMaterial
References CrypticCabinet.SceneManagement.DeskSpaceFinder.DeskSize, and CrypticCabinet.SceneManagement.DeskSpaceFinder.RememberDistanceField().
GetFinderSize()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.GetFinderSize (out Vector3 worldSize)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
GetFinderTransform()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.GetFinderTransform (out Matrix4x4 localToWorldMatrix)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
HasSetUpCompleted()
bool CrypticCabinet.SceneManagement.DeskSpaceFinder.HasSetUpCompleted ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
RememberDistanceField()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.RememberDistanceField ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
Referenced by CrypticCabinet.SceneManagement.DeskSpaceFinder.CalculateBlockedArea(), and CrypticCabinet.SceneManagement.DeskSpaceFinder.GenerateDeskCells().
RequestCenterLocation()
bool CrypticCabinet.SceneManagement.DeskSpaceFinder.RequestCenterLocation (float radius, out Vector3 foundPosition, bool markAsBlocked = false, float edgeDistance = -1)
Returns a location on the desk for a given radius, if there's no location that can safely place the object returns false.
Parameters
radius Radius of the object to place.
foundPosition The found position in world space.
markAsBlocked Updates the distance field to be blocked once placed.
Returns
True if the returns position is valid, false if not.
Referenced by CrypticCabinet.SceneManagement.DeskSpaceFinder.RequestRandomLocation().
RequestRandomLocation() [1/2]
bool CrypticCabinet.SceneManagement.DeskSpaceFinder.RequestRandomLocation (Vector3 locationToFace, float objectRadius, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked = false, float edgeDistance = -1)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
References CrypticCabinet.SceneManagement.DeskSpaceFinder.RequestCenterLocation().
RequestRandomLocation() [2/2]
bool CrypticCabinet.SceneManagement.DeskSpaceFinder.RequestRandomLocation (Vector3 locationToFace, Vector3 objectDimensions, out Vector3 foundPosition, out Quaternion foundRotation, bool markAsBlocked = false)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
RequestTrulyRandomLocation()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.RequestTrulyRandomLocation (out Vector3 position)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
ResetDistanceField()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.ResetDistanceField ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
SetDebugViewEnabled()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.SetDebugViewEnabled (bool isVisible)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
SetSearchCollidersActive()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.SetSearchCollidersActive (bool collidersActive)
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
ToggleDebugView()
void CrypticCabinet.SceneManagement.DeskSpaceFinder.ToggleDebugView ()
Implements CrypticCabinet.SceneManagement.ISpaceFinder.
Member Data Documentation
DeskSize
Vector2 CrypticCabinet.SceneManagement.DeskSpaceFinder.DeskSize
The width and depth of the desk.
Referenced by CrypticCabinet.SceneManagement.DeskSpaceFinder.GenerateDeskCells().
The documentation for this class was generated from the following file:
DeskSpaceFinder.cs